FROM oven/bun AS build

WORKDIR /app

COPY . .

RUN bun install

ENV NODE_ENV=production

RUN bun build --compile --minify-whitespace --minify-syntax --outfile cronserver src/cronjobs/server.ts

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=build /app/cronserver cronserver

ENV NODE_ENV=production

EXPOSE 3001

CMD ["./cronserver"]
