FROM oven/bun AS build

WORKDIR /app

COPY . .

RUN bun install

ENV NODE_ENV=production

RUN bun build --compile --minify-whitespace --minify-syntax --outfile tgbot src/index.ts

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=build /app/tgbot tgbot

ENV NODE_ENV=production

CMD ["./tgbot"]
