export const CALLBACK_DATA = {
  SETTINGS_LANGUAGE: "settings_language",
  SETTINGS_CHANNELS: "settings_channels",
  SETTINGS_SUPPORT: "settings_support",
  SETTINGS_BACK: "settings_back",
  SETTINGS_CLOSE: "settings_close",
  PROPERTY_CLAIM: "property_claim",
  PROPERTY_CLOSE: "property_close",
  PROPERTY_BACK: "property_back",
  PROPERTY_UPGRADE: "property_upgrade",
  BOARD_BUY_PROPERTY: "board_buy_property",
  BOARD_BUY_SERVICE: "board_buy_service",
  SERVICE_CLOSE: "service_close",
  SERVICE_BACK: "service_back",
  MINIGAME_CANCEL: "minigame_cancel",
  REFERRAL_HISTORY: "referral_history",
  REFERRAL_REFRESH: "referral_refresh",
  REFERRAL_CLOSE: "referral_close",
  WITHDRAWAL_MENU: "withdrawal_menu",
  WITHDRAWAL_CREATE: "withdrawal_create",
  WITHDRAWAL_HISTORY: "withdrawal_history",
  WITHDRAWAL_CANCEL: "withdrawal_cancel",
  ADMIN_PANEL: "admin_panel",
  ADMIN_USERS: "admin_users",
  ADMIN_TOP_USERS: "admin_top_users",
  ADMIN_WITHDRAWALS: "admin_withdrawals",
  ADMIN_PENDING_WITHDRAWALS: "admin_pending_withdrawals",
  ADMIN_BACK: "admin_back",
  ADMIN_CLOSE: "admin_close",
} as const;

export const CALLBACK_PATTERNS = {
  LANGUAGE: /^lang_(ru|en|es|pt)$/,
  START_REFERRAL: /^\/start\s+(\S+)$/,
  PROPERTY_NAV: /^property_nav_(\d+)$/,
  PROPERTY_CLAIM: /^property_claim_(\d+)$/,
  PROPERTY_UPGRADE: /^property_upgrade_(\d+)$/,
  SERVICE_NAV: /^service_nav_(\d+)$/,
  BOARD_BUY_PROPERTY: /^board_buy_property_(\d+)$/,
  BOARD_BUY_SERVICE: /^board_buy_service_(\d+)$/,
  MINIGAME_SELECT: /^minigame_(dice|darts|basketball|football|bowling|slots)$/,
  MINIGAME_DICE_PICK: /^dice_pick_([1-6])$/,
  WITHDRAWAL_CURRENCY: /^withdrawal_currency_(bitcoin|usdt_tron|monero)$/,
  WITHDRAWAL_HISTORY: /^withdrawal_history_(\d+)$/,
  WITHDRAWAL_ADMIN_VIEW: /^withdrawal_admin_view_(\d+)$/,
  WITHDRAWAL_ADMIN_PROCESS: /^withdrawal_admin_process_(\d+)$/,
  WITHDRAWAL_ADMIN_CANCEL: /^withdrawal_admin_cancel_(\d+)$/,
  WITHDRAWAL_ADMIN_REFUND: /^withdrawal_admin_refund_(\d+)$/,
  ADMIN_USERS_PAGE: /^admin_users_page_(\d+)$/,
} as const;

export const WITHDRAWAL_CURRENCIES = [
  "bitcoin",
  "usdt_tron",
  "monero",
] as const;
export const WITHDRAWAL_STATUSES = [
  "pending",
  "processed",
  "cancelled",
  "refunded",
] as const;
