export const CALLBACK_DATA = {
  SETTINGS_LANGUAGE: "settings_language",
  SETTINGS_CHANNELS: "settings_channels",
  SETTINGS_SUPPORT: "settings_support",
  SETTINGS_BACK: "settings_back",
  SETTINGS_CLOSE: "settings_close",
  PROPERTY_CLAIM: "property_claim",
  PROPERTY_CLOSE: "property_close",
  PROPERTY_BACK: "property_back",
  PROPERTY_UPGRADE: "property_upgrade",
  BOARD_BUY_PROPERTY: "board_buy_property",
  BOARD_BUY_SERVICE: "board_buy_service",
  SERVICE_CLOSE: "service_close",
  SERVICE_BACK: "service_back",
  MINIGAME_CANCEL: "minigame_cancel",
  MINIGAME_EXIT: "minigame_exit",
  REFERRAL_HISTORY: "referral_history",
  REFERRAL_REFRESH: "referral_refresh",
  REFERRAL_CLOSE: "referral_close",
  WITHDRAWAL_MENU: "withdrawal_menu",
  WITHDRAWAL_CREATE: "withdrawal_create",
  WITHDRAWAL_HISTORY: "withdrawal_history",
  WITHDRAWAL_CANCEL: "withdrawal_cancel",
  ADMIN_PANEL: "admin_panel",
  ADMIN_USERS: "admin_users",
  ADMIN_TOP_USERS: "admin_top_users",
  ADMIN_WITHDRAWALS: "admin_withdrawals",
  ADMIN_PENDING_WITHDRAWALS: "admin_pending_withdrawals",
  ADMIN_BACK: "admin_back",
  ADMIN_CLOSE: "admin_close",
  DEPOSIT_MENU: "deposit_menu",
  DEPOSIT_CREATE: "deposit_create",
  DEPOSIT_HISTORY: "deposit_history",
  DEPOSIT_CANCEL: "deposit_cancel",
  DEPOSIT_CRYPTO_BACK: "deposit_crypto_back",
  TERMS_ACCEPT: "terms_accept",
  TERMS_DECLINE: "terms_decline",
  DEPOSIT_SECURITY_CONFIRM: "deposit_security_confirm",
  DEPOSIT_SECURITY_CANCEL: "deposit_security_cancel",
} as const;

export const CALLBACK_PATTERNS = {
  LANGUAGE: /^lang_(ru|en|es|pt)$/,
  START_REFERRAL: /^\/start\s+(\S+)$/,
  PROPERTY_NAV: /^property_nav_(\d+)$/,
  PROPERTY_CLAIM: /^property_claim_(\d+)$/,
  PROPERTY_UPGRADE: /^property_upgrade_(\d+)$/,
  PROPERTY_COLOR: /^property_color_(brown|orange|red|blue)_(\d+)$/,
  SERVICE_NAV: /^service_nav_(\d+)$/,
  BOARD_BUY_PROPERTY: /^board_buy_property_(\d+)$/,
  BOARD_BUY_SERVICE: /^board_buy_service_(\d+)$/,
  MINIGAME_SELECT: /^minigame_(dice|darts|basketball|football|bowling|slots)$/,
  MINIGAME_DICE_PICK: /^dice_pick_([1-6])$/,
  MINIGAME_BET_ADJUST: /^bet_adjust_(-?\d+)$/,
  WITHDRAWAL_CURRENCY: /^withdrawal_currency_(bitcoin|usdt_tron|monero)$/,
  WITHDRAWAL_HISTORY: /^withdrawal_history_(\d+)$/,
  WITHDRAWAL_ADMIN_VIEW: /^withdrawal_admin_view_(\d+)$/,
  WITHDRAWAL_ADMIN_PROCESS: /^withdrawal_admin_process_(\d+)$/,
  WITHDRAWAL_ADMIN_CANCEL: /^withdrawal_admin_cancel_(\d+)$/,
  WITHDRAWAL_ADMIN_REFUND: /^withdrawal_admin_refund_(\d+)$/,
  ADMIN_USERS_PAGE: /^admin_users_page_(\d+)$/,
  DEPOSIT_HISTORY: /^deposit_history_(\d+)$/,
  DEPOSIT_CRYPTO:
    /^deposit_crypto_(btc|eth|usdttrc20|usdc|ltc|bch|bnbbsc|sol)$/,
  TERMS_ACCEPT: /^terms_accept$/,
  TERMS_DECLINE: /^terms_decline$/,
  DEPOSIT_SECURITY_CONFIRM: /^deposit_security_confirm$/,
  DEPOSIT_SECURITY_CANCEL: /^deposit_security_cancel$/,
} as const;

export const WITHDRAWAL_CURRENCIES = [
  "bitcoin",
  "usdt_tron",
  "monero",
] as const;
export const WITHDRAWAL_STATUSES = [
  "pending",
  "processed",
  "cancelled",
  "refunded",
] as const;

export const AVAILABLE_CRYPTO_CURRENCIES = [
  { code: "btc", name: "Bitcoin", symbol: "BTC", network: "Bitcoin" },
  { code: "eth", name: "Ethereum", symbol: "ETH", network: "ERC20" },
  { code: "usdttrc20", name: "Tether", symbol: "USDT", network: "TRC20" },
  { code: "usdc", name: "USD Coin", symbol: "USDC", network: "ERC20" },
  { code: "ltc", name: "Litecoin", symbol: "LTC", network: "Litecoin" },
  { code: "bch", name: "Bitcoin Cash", symbol: "BCH", network: "BCH" },
  { code: "bnbbsc", name: "BNB", symbol: "BNB", network: "BEP20" },
  { code: "sol", name: "Solana", symbol: "SOL", network: "Solana" },
] as const;
